### ISSUE TITLE
IDs in Attributes

### ISSUE THREAD

**Issue by pixelremix** [ZiZuu-store/zzCleanURLs#42]
IDs are still present in attributes when looking at a product.

eg. category/product#/13-color-orange

Is there any way to remove the ID from attributes also?

**Comment by ZiZuu-store** [comment]
Nowadays it is not supported .. Will look deeper for a future implementation

**Comment by ZiZuu-store** [comment]
@pixelremix I think this is an issue with your theme .. 

AFAICS this URL is correct https://zizuu.com/calamite-da-collezione/#/Prezzo-5.24-11 .. isn't it?

Waiting for your feedback, thanks

**Comment by pixelremix** [comment]
@ZiZuu-store I'm using the default theme.

That URL is correct, but that item doesn't have extra attributes.

For example, this item from your store

https://zizuu.com/stampi-in-silicone-per-muffin-e-cupcake/stampi-mignon-micro-bundt-cake-nordic-style-in-silicone-3pz#/11-colore-fucsia

You can see that ID 11 is added to the color fuscia, and any other color variant there is an ID.

**Comment by ZiZuu-store** [comment]
@pixelremix OK got tour point 

Will go deeper .. 

Thanks

**Comment by misthero** [comment]
I would like to say that those are not real PHP "rewritten url", those are hashes used only by javascript to select the correct image, highlight the variations and such minor aestetic differences, but the page is not reloaded, the javascript doing that is product.js and I think this has nothing to do with this module and it's out of it's scope.

an hash is not part of the url and can be anything the page will still work, example:

https://zizuu.com/stampi-in-silicone-per-muffin-e-cupcake/stampi-mignon-micro-bundt-cake-nordic-style-in-silicone-3pz#/11-look-at-this-hash-with-some-random-text-it-still-highlight-the-FUCSIA-because-there-is-eleven-MAGIC!!

https://zizuu.com/stampi-in-silicone-per-muffin-e-cupcake/stampi-mignon-micro-bundt-cake-nordic-style-in-silicone-3pz#OH-MY-GOD-LOOK-AT-THIS FUNNY-URL!!!!!!-here-there-is-no-fucsia-selected

More than this using a different theme could change that behaviour. since it is at theme level

I think this module should keep doing and improving what is doing best. 

Just my 2 cents :)

**Comment by ZiZuu-store** [comment]
@misthero thank you for your explanation and I'm of your opinion too.

I think tomorrow will close this issue if neither the night nor anybody else will rise any opposition :)

**Comment by ZiZuu-store** [comment]
@misthero thank you for your explanation and I'm of your opinion too.

I think tomorrow will close this issue if neither the night nor anybody else will rise any opposition :)

**Comment by ZiZuu-store** [comment]
As this is a JS issue and this module can't handle it, even willing I close this issue.

 I think js ids do not affect SEO, at least when not in the form `#!` that is used for AJAX 

Thank you everybody
