### ISSUE TITLE
Delete Query string 

### ISSUE THREAD

**Issue by simonwiller** [ZiZuu-store/zzCleanURLs#53]
Hi, 

Thanks for the module. 

I have a question. When does the module actually delete query strings. I thought that it would delete it on pages with pagination like my category pages. But as fare I can see it only inserts <link rel="canonical" href="full url"> and does not delete the query strings which imho is the the point of installing af module like this - right?

All the best

**Comment by ZiZuu-store** [comment]
Hello,
  the intended behavior is to remove the ID from the URLs and make the webmaster to choose a better URL schema than the default one

To accomplish this task *zzCleanURLs* overrides same core classes. Only a minimal part of the overridden code is changed and it regards the ID handling only.

The QS handling should be the same of the default PS core.

We have developed another module, **[ZiZuu SEO ToolKit](https://github.com/ZiZuu-store/zzSEOtk)**, with the scope of handling SEO related issues. This module can add a *canonical* meta tag to your pages that assures no duplicate content is shown to search engines.

About the QS issue **[zzSEOtk](https://github.com/ZiZuu-store/zzSEOtk)** module behaves as follow:
- strip the QS
- re-add **only** the "`p`" parameter on pages where `p > 1`

This is the right SEO-friendly behavior because in PS every page has different content and there is no duplicate issue, while other QS parameters simply filter or reorder the page content not giving any unique content.

Hope I have clarified this module intent and asked your question :)
